FROM node:20-bookworm
WORKDIR /app

ENV SATISFACTORY_BOT_DOCKER=1
ENV SATISFACTORY_BOT_DB_PATH=/data/db.json
ENV SATISFACTORY_BOT_DISABLE_UNREACHABLE_FOUND_MESSAGES=false
ENV SATISFACTORY_BOT_DISCORD_CHANNEL_NAME=
ENV SATISFACTORY_BOT_DISCORD_SERVER_NAME=
ENV SATISFACTORY_BOT_DISCORD_TOKEN=YOUR_DISCORD_TOKEN
ENV SATISFACTORY_BOT_IGNORE_POLL_STATE_WHEN_MESSAGING=false
ENV SATISFACTORY_BOT_LOG_LOCATION=/logs/FactoryGame.log
ENV SATISFACTORY_BOT_POLL_INTERVAL_MINUTES=1
ENV SATISFACTORY_BOT_PURGE_DISCORD_CHANNEL_AFTER_DAYS=7
ENV SATISFACTORY_BOT_PURGE_DISCORD_CHANNEL_AFTER_LINES=
ENV SATISFACTORY_BOT_PURGE_DISCORD_CHANNEL_HOUR=2
ENV SATISFACTORY_BOT_PURGE_DISCORD_CHANNEL_NAME=
ENV SATISFACTORY_BOT_PURGE_DISCORD_CHANNEL_SERVER_NAME=
ENV SATISFACTORY_BOT_SERVER_IP=server
ENV SATISFACTORY_BOT_SERVER_MAX_PLAYERS=4
ENV SATISFACTORY_BOT_SERVER_QUERY_PORT=15777
ENV SATISFACTORY_BOT_SERVER_QUERY_TIMEOUT_MS=10000

COPY package.json package-lock.json /app/
RUN npm install
COPY bin/ /app/bin/
COPY src/ /app/src/

CMD [ "npm", "start" ]
